version: "3.8"
services:
  web:
    build:
      context: .            # relative to backend/, so run docker-compose from backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - ENV=prod
      - GCS_ENABLED=true
      - GCS_BUCKET=filetagapi-uploads-filetagapi-prod
      # Add GOOGLE_APPLICATION_CREDENTIALS env only if you use a JSON key file (not recommended)
    volumes:
      - /srv/filetagapi/uploads:/app/uploads     # host persistent uploads AND DB files if your app stored auth.db in uploads
    command: uvicorn app:app --host 0.0.0.0 --port 8080
    restart: unless-stopped
