name: Build & Deploy to Cloud Run

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    environment: ${{ contains(github.ref, 'refs/heads/main') && 'production' || 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Authenticate to GCP using the service account JSON stored in secrets.GCP_SA_KEY
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # (optional) Install gcloud CLI (setup-gcloud will still be helpful for region/project)
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Configure Docker to use gcloud credentials for gcr.io
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker image (backend)
        run: |
          cd backend
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT }}/filetagapi:${{ github.sha }}"
          docker build -t "$IMAGE" .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push Docker image to GCR
        run: |
          cd backend
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        env:
          IMAGE: ${{ env.IMAGE }}
          REGION: ${{ secrets.GCP_REGION }}
          BUCKET: ${{ secrets.GCS_BUCKET }}
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            SERVICE="filetagapi-prod"
            ENVIRONMENT="prod"
          else
            SERVICE="filetagapi-dev"
            ENVIRONMENT="dev"
          fi
          echo "Deploying $IMAGE to $SERVICE in region ${REGION}"
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --service-account=filetagapi-runner-sa@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com \
            --set-env-vars="ENV=${ENVIRONMENT},GCS_ENABLED=true,GCS_BUCKET=${BUCKET}" \
            --quiet

      - name: Output Cloud Run URL
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            SERVICE="filetagapi-prod"
          else
            SERVICE="filetagapi-dev"
          fi
          gcloud run services describe "$SERVICE" --region="${{ secrets.GCP_REGION }}" --platform=managed --format="value(status.url)"
